# Generated by Django 5.0.6 on 2024-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Blue-white', 'Blue-white'), ('blue-burquoise', 'blue-burquoise'), ('pink-silver', 'pink-silver'), ('fillet', 'fillet'), ('purple-white', 'purple-white'), ('pearl-golden', 'pearl-golden'), ('blue-golden', 'blue-golden')], default='Blue-white', max_length=255),
        ),
    ]
