# Generated by Django 5.1.5 on 2025-01-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_rename_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
