# Generated by Django 5.0.6 on 2024-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
