# Generated by Django 5.0.6 on 2024-08-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0009_shippingaddress_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
